name: unidata-std-pytorch
channels:
  - conda-forge
  # Begin pytorch channels  
  - pytorch
  - nvidia
  # End pytorch channels  
dependencies:
  # Required by JupyterLab
  - python=3
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - numpy
  - matplotlib
  - cartopy
  - metpy
  - siphon
  - pandas
  - pip
  - xarray
  - ipywidgets
  - python-awips
  - scikit-learn
  # Begin pytorch dependencies
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  # End pytorch dependencies
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - palmerpenguins
